server:
  port: 80

paymentUrl:
  #url: http://localhost:8001
  url: http://CLOUD-PAYMENT-SERVICE

spring:
  #服务名称
  application:
    name: cloud-order-service

  datasource:
    #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.payment.springcloud.entities #所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true.
    register-with-eureka: true
    #是否从EurekaServer 抓取已有的注册信息，默认为true.单点无所谓，集群必须是true 才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: orderConsumer80
    prefer-ip-address: true #访问路径可以显示IP地址
